"""initial schema

Revision ID: 1d6748a7402d
Revises:
Create Date: 2026-09-12 17:25:53.735801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d6748a7402d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions first. docker compose creates these via ops/initdb on first
    # initialisation of the volume, but a database created any other way -- a
    # managed instance, a restore into an empty volume -- would not have them,
    # and every table below depends on them. Creating extensions needs superuser;
    # if that ever stops being true, this is the block that has to move.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "preferred_lang",
            sa.Enum("mk", "sq", "en", "tr", name="lang"),
            server_default=sa.text("'mk'"),
            nullable=False,
        ),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anonymised_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
        sa.UniqueConstraint("email", name=op.f("uq_account_email")),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name_mk", sa.Text(), nullable=False),
        sa.Column("price_mkd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "vat_rate",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("18.00"),
            nullable=False,
        ),
        sa.Column("is_recurring", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("sku", name=op.f("uq_product_sku")),
    )
    op.create_table(
        "prompt_version",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("task", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_version")),
    )
    op.create_table(
        "source_feed",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name_mk", sa.Text(), nullable=False),
        sa.Column("name_en", sa.Text(), nullable=False),
        sa.Column("institution", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column(
            "access_method",
            sa.Enum("api", "rss", "html", "pdf_index", "manual", name="access_method"),
            nullable=False,
        ),
        sa.Column("robots_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_url", sa.Text(), nullable=True),
        sa.Column("terms_note", sa.Text(), nullable=True),
        sa.Column("expected_cadence", sa.Interval(), nullable=False),
        sa.Column("staleness_sla", sa.Interval(), nullable=False),
        sa.Column(
            "rate_limit_rps",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0.2"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("100"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_feed")),
        sa.UniqueConstraint("slug", name=op.f("uq_source_feed_slug")),
    )
    op.create_table(
        "applicant_profile",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "sole_trader",
                "micro",
                "small",
                "medium",
                "large",
                "ngo",
                "municipality",
                "individual",
                "farm",
                "startup",
                "other",
                name="entity_type",
            ),
            nullable=False,
        ),
        sa.Column("nace_code", sa.String(length=10), nullable=True),
        sa.Column("municipality_code", sa.String(length=20), nullable=True),
        sa.Column("region_code", sa.String(length=20), nullable=True),
        sa.Column("founded_year", sa.SmallInteger(), nullable=True),
        sa.Column("headcount", sa.Integer(), nullable=True),
        sa.Column("turnover_band_mkd", sa.String(length=50), nullable=True),
        sa.Column("is_woman_owned", sa.Boolean(), nullable=True),
        sa.Column("is_youth_owned", sa.Boolean(), nullable=True),
        sa.Column("is_export_oriented", sa.Boolean(), nullable=True),
        sa.Column("investment_type", sa.Text(), nullable=True),
        sa.Column("investment_size_mkd", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("cofinancing_capable_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("timeline_months", sa.SmallInteger(), nullable=True),
        sa.Column("project_keywords", sa.Text(), nullable=True),
        sa.Column("project_description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_applicant_profile_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applicant_profile")),
    )
    op.create_index(
        "ix_profile_account",
        "applicant_profile",
        ["account_id", sa.literal_column("version DESC")],
        unique=False,
    )
    op.create_table(
        "consent_record",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=50), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_consent_record_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_record")),
    )
    op.create_index(
        "ix_consent_account",
        "consent_record",
        ["account_id", "purpose", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "email_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bounced", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_email_event_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_event")),
    )
    op.create_index(
        "ix_email_account",
        "email_event",
        ["account_id", sa.literal_column("sent_at DESC")],
        unique=False,
    )
    op.create_table(
        "ingestion_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_feed_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("urls_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("urls_changed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("queued_for_review", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_feed_id"],
            ["source_feed.id"],
            name=op.f("fk_ingestion_run_source_feed_id_source_feed"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_run")),
    )
    op.create_index(
        "ix_ingestion_run_source_time",
        "ingestion_run",
        ["source_feed_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "programme",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_feed_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("name_mk", sa.Text(), nullable=False),
        sa.Column("name_sq", sa.Text(), nullable=True),
        sa.Column("name_en", sa.Text(), nullable=True),
        sa.Column("institution", sa.Text(), nullable=False),
        sa.Column("description_mk", sa.Text(), nullable=True),
        sa.Column("is_singleton", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("typical_cadence", sa.Interval(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_feed_id"],
            ["source_feed.id"],
            name=op.f("fk_programme_source_feed_id_source_feed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programme")),
        sa.UniqueConstraint("slug", name=op.f("uq_programme_slug")),
    )
    op.create_table(
        "raw_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_feed_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("byte_length", sa.Integer(), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("normalised_text", sa.Text(), nullable=True),
        sa.Column("normaliser_version", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_feed_id"],
            ["source_feed.id"],
            name=op.f("fk_raw_snapshot_source_feed_id_source_feed"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_snapshot")),
        sa.UniqueConstraint("url", "content_sha256", name="uq_raw_snapshot_url_hash"),
    )
    op.create_index("ix_snapshot_hash", "raw_snapshot", ["content_sha256"], unique=False)
    op.create_index(
        "ix_snapshot_url_time",
        "raw_snapshot",
        ["url", sa.literal_column("fetched_at DESC")],
        unique=False,
    )
    op.create_table(
        "source_health",
        sa.Column("source_feed_id", sa.Uuid(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_new_item_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("is_alerting", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_feed_id"],
            ["source_feed.id"],
            name=op.f("fk_source_health_source_feed_id_source_feed"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_feed_id", name=op.f("pk_source_health")),
    )
    op.create_table(
        "call",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("programme_id", sa.Uuid(), nullable=False),
        sa.Column("source_feed_id", sa.Uuid(), nullable=False),
        sa.Column("reference_code", sa.Text(), nullable=True),
        sa.Column("title_mk", sa.Text(), nullable=False),
        sa.Column("title_sq", sa.Text(), nullable=True),
        sa.Column("title_en", sa.Text(), nullable=True),
        sa.Column("summary_mk", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "open", "closed", "cancelled", "announced", name="call_status"),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("opens_at", sa.Date(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_budget_mkd", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("total_budget_eur", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("grant_min_mkd", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("grant_max_mkd", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("cofinancing_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "allowed_entity_types",
            postgresql.ARRAY(
                sa.Enum(
                    "sole_trader",
                    "micro",
                    "small",
                    "medium",
                    "large",
                    "ngo",
                    "municipality",
                    "individual",
                    "farm",
                    "startup",
                    "other",
                    name="entity_type",
                )
            ),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "allowed_nace_prefixes",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "allowed_regions",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("min_company_age_months", sa.Integer(), nullable=True),
        sa.Column("max_company_age_months", sa.Integer(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("primary_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "last_verified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("extraction_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["primary_snapshot_id"],
            ["raw_snapshot.id"],
            name=op.f("fk_call_primary_snapshot_id_raw_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["programme_id"],
            ["programme.id"],
            name=op.f("fk_call_programme_id_programme"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_feed_id"], ["source_feed.id"], name=op.f("fk_call_source_feed_id_source_feed")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call")),
    )
    op.create_index(
        "ix_call_entity_types",
        "call",
        ["allowed_entity_types"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_call_nace", "call", ["allowed_nace_prefixes"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_call_open",
        "call",
        ["status", "deadline_at"],
        unique=False,
        postgresql_where=sa.text("is_published AND status = 'open'"),
    )
    op.create_index(
        "ix_call_programme",
        "call",
        ["programme_id", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_call_regions", "call", ["allowed_regions"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_call_title_trgm",
        "call",
        ["title_mk"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_mk": "gin_trgm_ops"},
    )
    op.create_table(
        "document_template",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("programme_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column(
            "lang",
            sa.Enum("mk", "sq", "en", "tr", name="lang"),
            server_default=sa.text("'mk'"),
            nullable=False,
        ),
        sa.Column(
            "required_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["programme_id"],
            ["programme.id"],
            name=op.f("fk_document_template_programme_id_programme"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_template")),
        sa.UniqueConstraint("programme_id", "slug", "version", name="uq_document_template_version"),
    )
    op.create_table(
        "match_run",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("ruleset_version", sa.String(length=50), nullable=False),
        sa.Column("weights_version", sa.String(length=50), nullable=False),
        sa.Column("stage_reached", sa.SmallInteger(), nullable=False),
        sa.Column("candidates_considered", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["applicant_profile.id"],
            name=op.f("fk_match_run_profile_id_applicant_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_run")),
    )
    op.create_index(
        "ix_match_run_profile",
        "match_run",
        ["profile_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "subscription",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("renews_on", sa.Date(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_alert_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_subscription_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_subscription_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["applicant_profile.id"],
            name=op.f("fk_subscription_profile_id_applicant_profile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
    )
    op.create_index(
        "ix_subscription_due",
        "subscription",
        ["renews_on"],
        unique=False,
        postgresql_where=sa.text("cancelled_at IS NULL"),
    )
    op.create_table(
        "call_document",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"], ["call.id"], name=op.f("fk_call_document_call_id_call"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshot.id"],
            name=op.f("fk_call_document_snapshot_id_raw_snapshot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_document")),
    )
    op.create_index("ix_call_document_call", "call_document", ["call_id"], unique=False)
    op.create_table(
        "chunk",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"], ["call.id"], name=op.f("fk_chunk_call_id_call"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshot.id"],
            name=op.f("fk_chunk_snapshot_id_raw_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunk")),
        sa.UniqueConstraint("snapshot_id", "ordinal", name="uq_chunk_snapshot_ordinal"),
    )
    op.create_index("ix_chunk_call", "chunk", ["call_id"], unique=False)
    op.create_index(
        "ix_chunk_embedding",
        "chunk",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_chunk_text_trgm",
        "chunk",
        ["text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    )
    op.create_table(
        "eligibility_criterion",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "hard_structured",
                "soft_scored",
                "narrative_verify",
                "applicant_attest",
                "documentary",
                name="criterion_kind",
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=100), nullable=True),
        sa.Column("label_mk", sa.Text(), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=True),
        sa.Column("operator", sa.String(length=20), nullable=True),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("weight", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("source_quote", sa.Text(), nullable=True),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("quote_start", sa.Integer(), nullable=True),
        sa.Column("quote_end", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "kind <> 'hard_structured' OR (field IS NOT NULL AND operator IS NOT NULL)",
            name=op.f("ck_eligibility_criterion_structured_has_predicate"),
        ),
        sa.CheckConstraint(
            "NOT is_approved OR (snapshot_id IS NOT NULL AND source_quote IS NOT NULL)",
            name=op.f("ck_eligibility_criterion_has_citation"),
        ),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["call.id"],
            name=op.f("fk_eligibility_criterion_call_id_call"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshot.id"],
            name=op.f("fk_eligibility_criterion_snapshot_id_raw_snapshot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility_criterion")),
    )
    op.create_index("ix_criterion_call", "eligibility_criterion", ["call_id", "kind"], unique=False)
    op.create_table(
        "match_result",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("match_run_id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "eligible", "likely_eligible", "needs_verification", "not_eligible", name="verdict"
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"], ["call.id"], name=op.f("fk_match_result_call_id_call"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["match_run_id"],
            ["match_run.id"],
            name=op.f("fk_match_result_match_run_id_match_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_result")),
        sa.UniqueConstraint("match_run_id", "call_id", name="uq_match_result_run_call"),
    )
    op.create_index("ix_match_result_run", "match_result", ["match_run_id", "rank"], unique=False)
    op.create_table(
        "model_call",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task", sa.String(length=50), nullable=False),
        sa.Column("prompt_version_id", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("validation_error", sa.Text(), nullable=True),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("match_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["call.id"], name=op.f("fk_model_call_call_id_call"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["match_run_id"],
            ["match_run.id"],
            name=op.f("fk_model_call_match_run_id_match_run"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_version.id"],
            name=op.f("fk_model_call_prompt_version_id_prompt_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_call")),
    )
    op.create_index("ix_model_call_cache", "model_call", ["input_hash"], unique=False)
    op.create_index(
        "ix_model_call_cost",
        "model_call",
        [sa.literal_column("created_at DESC"), "task"],
        unique=False,
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("match_run_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "created",
                "invoiced",
                "paid",
                "in_progress",
                "delivered",
                "cancelled",
                "refunded",
                name="order_state",
            ),
            server_default=sa.text("'created'"),
            nullable=False,
        ),
        sa.Column("amount_mkd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("vat_mkd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "provider", sa.String(length=30), server_default=sa.text("'invoice'"), nullable=False
        ),
        sa.Column("buyer_name", sa.Text(), nullable=True),
        sa.Column("buyer_address", sa.Text(), nullable=True),
        sa.Column("buyer_edb", sa.String(length=20), nullable=True),
        sa.Column("buyer_embs", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_order_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_run_id"], ["match_run.id"], name=op.f("fk_order_match_run_id_match_run")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_order_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["applicant_profile.id"],
            name=op.f("fk_order_profile_id_applicant_profile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
    )
    op.create_index(
        "ix_order_account",
        "order",
        ["account_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_order_state", "order", ["state", "created_at"], unique=False)
    op.create_table(
        "document_package",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("pending", "approved", "edited", "rejected", name="review_state"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "checklist",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"], ["call.id"], name=op.f("fk_document_package_call_id_call")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
            name=op.f("fk_document_package_order_id_order"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_package")),
    )
    op.create_table(
        "invoice",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind", sa.Enum("proforma", "final", "credit_note", name="invoice_kind"), nullable=False
        ),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("fiscal_year", sa.SmallInteger(), nullable=False),
        sa.Column("issued_at", sa.Date(), nullable=False),
        sa.Column("due_at", sa.Date(), nullable=True),
        sa.Column("amount_mkd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("vat_mkd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_mkd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("pdf_storage_key", sa.Text(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bank_reference", sa.Text(), nullable=True),
        sa.Column("reconciled_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("fk_invoice_order_id_order"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["reconciled_by"], ["account.id"], name=op.f("fk_invoice_reconciled_by_account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice")),
        sa.UniqueConstraint("number", name=op.f("uq_invoice_number")),
    )
    op.create_index(
        "ix_invoice_unpaid",
        "invoice",
        ["issued_at"],
        unique=False,
        postgresql_where=sa.text("paid_at IS NULL"),
    )
    op.create_table(
        "match_criterion_outcome",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("match_result_id", sa.BigInteger(), nullable=False),
        sa.Column("criterion_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "eligible", "likely_eligible", "needs_verification", "not_eligible", name="verdict"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("decided_by", sa.String(length=10), nullable=False),
        sa.Column("reason_mk", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criterion_id"],
            ["eligibility_criterion.id"],
            name=op.f("fk_match_criterion_outcome_criterion_id_eligibility_criterion"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["match_result_id"],
            ["match_result.id"],
            name=op.f("fk_match_criterion_outcome_match_result_id_match_result"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_criterion_outcome")),
        sa.UniqueConstraint("match_result_id", "criterion_id", name="uq_outcome_result_criterion"),
    )
    op.create_table(
        "model_call_payload",
        sa.Column("model_call_id", sa.BigInteger(), nullable=False),
        sa.Column("request_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["model_call.id"],
            name=op.f("fk_model_call_payload_model_call_id_model_call"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("model_call_id", name=op.f("pk_model_call_payload")),
    )
    op.create_table(
        "review_queue_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "extraction", "report", "document_package", "source_health", name="review_kind"
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum("pending", "approved", "edited", "rejected", name="review_state"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("100"), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("match_run_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_note", sa.Text(), nullable=True),
        sa.Column("corrected_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["call.id"],
            name=op.f("fk_review_queue_item_call_id_call"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["match_run_id"],
            ["match_run.id"],
            name=op.f("fk_review_queue_item_match_run_id_match_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
            name=op.f("fk_review_queue_item_order_id_order"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["account.id"], name=op.f("fk_review_queue_item_reviewer_id_account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_queue_item")),
    )
    op.create_index(
        "ix_review_pending",
        "review_queue_item",
        ["state", "priority", "created_at"],
        unique=False,
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("outcome_id", sa.BigInteger(), nullable=True),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_id", sa.BigInteger(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("section_ref", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunk.id"], name=op.f("fk_evidence_chunk_id_chunk")
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["match_criterion_outcome.id"],
            name=op.f("fk_evidence_outcome_id_match_criterion_outcome"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["raw_snapshot.id"], name=op.f("fk_evidence_snapshot_id_raw_snapshot")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index("ix_evidence_outcome", "evidence", ["outcome_id"], unique=False)
    op.create_table(
        "generated_document",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("is_ai_assisted", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("human_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "unfilled_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["document_package.id"],
            name=op.f("fk_generated_document_package_id_document_package"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["document_template.id"],
            name=op.f("fk_generated_document_template_id_document_template"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_document")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("generated_document")
    op.drop_index("ix_evidence_outcome", table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(
        "ix_review_pending",
        table_name="review_queue_item",
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.drop_table("review_queue_item")
    op.drop_table("model_call_payload")
    op.drop_table("match_criterion_outcome")
    op.drop_index(
        "ix_invoice_unpaid", table_name="invoice", postgresql_where=sa.text("paid_at IS NULL")
    )
    op.drop_table("invoice")
    op.drop_table("document_package")
    op.drop_index("ix_order_state", table_name="order")
    op.drop_index("ix_order_account", table_name="order")
    op.drop_table("order")
    op.drop_index("ix_model_call_cost", table_name="model_call")
    op.drop_index("ix_model_call_cache", table_name="model_call")
    op.drop_table("model_call")
    op.drop_index("ix_match_result_run", table_name="match_result")
    op.drop_table("match_result")
    op.drop_index("ix_criterion_call", table_name="eligibility_criterion")
    op.drop_table("eligibility_criterion")
    op.drop_index(
        "ix_chunk_text_trgm",
        table_name="chunk",
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_chunk_embedding",
        table_name="chunk",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_chunk_call", table_name="chunk")
    op.drop_table("chunk")
    op.drop_index("ix_call_document_call", table_name="call_document")
    op.drop_table("call_document")
    op.drop_index(
        "ix_subscription_due",
        table_name="subscription",
        postgresql_where=sa.text("cancelled_at IS NULL"),
    )
    op.drop_table("subscription")
    op.drop_index("ix_match_run_profile", table_name="match_run")
    op.drop_table("match_run")
    op.drop_table("document_template")
    op.drop_index(
        "ix_call_title_trgm",
        table_name="call",
        postgresql_using="gin",
        postgresql_ops={"title_mk": "gin_trgm_ops"},
    )
    op.drop_index("ix_call_regions", table_name="call", postgresql_using="gin")
    op.drop_index("ix_call_programme", table_name="call")
    op.drop_index(
        "ix_call_open",
        table_name="call",
        postgresql_where=sa.text("is_published AND status = 'open'"),
    )
    op.drop_index("ix_call_nace", table_name="call", postgresql_using="gin")
    op.drop_index("ix_call_entity_types", table_name="call", postgresql_using="gin")
    op.drop_table("call")
    op.drop_table("source_health")
    op.drop_index("ix_snapshot_url_time", table_name="raw_snapshot")
    op.drop_index("ix_snapshot_hash", table_name="raw_snapshot")
    op.drop_table("raw_snapshot")
    op.drop_table("programme")
    op.drop_index("ix_ingestion_run_source_time", table_name="ingestion_run")
    op.drop_table("ingestion_run")
    op.drop_index("ix_email_account", table_name="email_event")
    op.drop_table("email_event")
    op.drop_index("ix_consent_account", table_name="consent_record")
    op.drop_table("consent_record")
    op.drop_index("ix_profile_account", table_name="applicant_profile")
    op.drop_table("applicant_profile")
    op.drop_table("source_feed")
    op.drop_table("prompt_version")
    op.drop_table("product")
    op.drop_table("account")
    # ### end Alembic commands ###
