"""call eligibility_gap

Revision ID: 3adfce186d77
Revises: c157abe6d901
Create Date: 2026-09-22 13:31:45.849229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "3adfce186d77"
down_revision: Union[str, Sequence[str], None] = "c157abe6d901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("call", sa.Column("eligibility_gap", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("call", "eligibility_gap")
    # ### end Alembic commands ###
