"""applicant profile answers

A match run (P2 s31) rebuilds its profile from the intake answers through stage 0,
so the answers are stored as given. The typed columns stay, filled where exact.

Revision ID: 426a03233500
Revises: 13672ae6492a
Create Date: 2026-09-24 10:44:57.932440

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "426a03233500"
down_revision: Union[str, Sequence[str], None] = "13672ae6492a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applicant_profile",
        sa.Column(
            "answers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applicant_profile", "answers")
    # ### end Alembic commands ###
