"""raw_snapshot last_seen_at

Revision ID: 96316a6b5511
Revises: 1d6748a7402d
Create Date: 2026-09-13 08:01:23.259835

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96316a6b5511"
down_revision: Union[str, Sequence[str], None] = "1d6748a7402d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_snapshot",
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # Existing snapshots were last seen when they were fetched, not when this ran.
    op.execute("UPDATE raw_snapshot SET last_seen_at = fetched_at")
    op.create_index(
        "ix_snapshot_url_seen",
        "raw_snapshot",
        ["url", sa.literal_column("last_seen_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshot_url_seen", table_name="raw_snapshot")
    op.drop_column("raw_snapshot", "last_seen_at")
    # ### end Alembic commands ###
