"""chunk belongs to snapshot; no vector index

Revision ID: c157abe6d901
Revises: db0ed2ef4bf3
Create Date: 2026-09-16 14:26:04.562122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c157abe6d901"
down_revision: Union[str, Sequence[str], None] = "db0ed2ef4bf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # P1 s12. Chunks are per snapshot and a call finds them through call_document;
    # call_id was never written. Retrieval scans one call's chunks exactly, and an
    # HNSW index under a WHERE filter can silently return fewer rows than asked for.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunk_call"), table_name="chunk")
    op.drop_index(
        op.f("ix_chunk_embedding"),
        table_name="chunk",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.drop_constraint(op.f("fk_chunk_call_id_call"), "chunk", type_="foreignkey")
    op.drop_column("chunk", "call_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunk", sa.Column("call_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("fk_chunk_call_id_call"), "chunk", "call", ["call_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(
        op.f("ix_chunk_embedding"),
        "chunk",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.create_index(op.f("ix_chunk_call"), "chunk", ["call_id"], unique=False)
    # ### end Alembic commands ###
