"""raw_snapshot text_source

Revision ID: db0ed2ef4bf3
Revises: 96316a6b5511
Create Date: 2026-09-13 08:15:08.980667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db0ed2ef4bf3"
down_revision: Union[str, Sequence[str], None] = "96316a6b5511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TEXT_SOURCE = sa.Enum("native", "ocr", "mixed", name="text_source")


def upgrade() -> None:
    """Upgrade schema."""
    # add_column does not create a PostgreSQL enum type the way create_table does.
    TEXT_SOURCE.create(op.get_bind(), checkfirst=True)
    op.add_column("raw_snapshot", sa.Column("text_source", TEXT_SOURCE, nullable=True))
    op.add_column(
        "raw_snapshot",
        sa.Column("ocr_mean_confidence", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_snapshot", "ocr_mean_confidence")
    op.drop_column("raw_snapshot", "text_source")
    TEXT_SOURCE.drop(op.get_bind(), checkfirst=True)
