"""Declarative base and shared column helpers."""

import datetime as dt
import uuid

from sqlalchemy import DateTime, Enum, MetaData, Uuid, func, text
from sqlalchemy.orm import DeclarativeBase, mapped_column

# Predictable constraint names, so a migration diff never turns on a generated
# identifier that changed between SQLAlchemy versions.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk():
    """UUID primary key generated by the database, not the application.

    Server-side so a row inserted by psql or a restore behaves like one inserted
    by the app.
    """
    return mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def now_column():
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


def timestamptz(**kwargs):
    return mapped_column(DateTime(timezone=True), **kwargs)


def pg_enum(enum_class, name: str) -> Enum:
    """A native PostgreSQL enum storing member VALUES, not member names.

    Without values_callable SQLAlchemy stores the Python names ("MICRO"), which
    would make the database unreadable in psql and break every hand-written query
    in docs/.
    """
    return Enum(
        enum_class,
        name=name,
        native_enum=True,
        values_callable=lambda members: [member.value for member in members],
    )


# Re-exported so model modules need one import for the common annotations.
__all__ = ["Base", "dt", "now_column", "pg_enum", "timestamptz", "uuid", "uuid_pk"]
