-- Generated by ops/dump-schema.sh from the live database. Do not edit.
-- Source of truth: app/models/ and migrations/. Rationale: docs/data-model.md.
-- Regenerate after every migration:  ./ops/dump-schema.sh

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Debian 16.15-1.pgdg12+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: access_method; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.access_method AS ENUM (
    'api',
    'rss',
    'html',
    'pdf_index',
    'manual'
);


--
-- Name: call_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.call_status AS ENUM (
    'draft',
    'open',
    'closed',
    'cancelled',
    'announced'
);


--
-- Name: criterion_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.criterion_kind AS ENUM (
    'hard_structured',
    'soft_scored',
    'narrative_verify',
    'applicant_attest',
    'documentary'
);


--
-- Name: entity_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.entity_type AS ENUM (
    'sole_trader',
    'craftsman',
    'micro',
    'small',
    'medium',
    'large',
    'ngo',
    'municipality',
    'individual',
    'farm',
    'startup',
    'other'
);


--
-- Name: invoice_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.invoice_kind AS ENUM (
    'proforma',
    'final',
    'credit_note'
);


--
-- Name: lang; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.lang AS ENUM (
    'mk',
    'sq',
    'en',
    'tr'
);


--
-- Name: order_state; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.order_state AS ENUM (
    'created',
    'invoiced',
    'paid',
    'in_progress',
    'delivered',
    'cancelled',
    'refunded'
);


--
-- Name: review_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.review_kind AS ENUM (
    'extraction',
    'verification',
    'report',
    'document_package',
    'source_health'
);


--
-- Name: review_state; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.review_state AS ENUM (
    'pending',
    'approved',
    'edited',
    'rejected'
);


--
-- Name: text_source; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.text_source AS ENUM (
    'native',
    'ocr',
    'mixed'
);


--
-- Name: verdict; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.verdict AS ENUM (
    'eligible',
    'likely_eligible',
    'needs_verification',
    'not_eligible'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email public.citext NOT NULL,
    email_verified_at timestamp with time zone,
    preferred_lang public.lang DEFAULT 'mk'::public.lang NOT NULL,
    is_admin boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone,
    anonymised_at timestamp with time zone
);


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: applicant_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.applicant_profile (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    superseded_at timestamp with time zone,
    label text,
    entity_type public.entity_type NOT NULL,
    nace_code character varying(10),
    municipality_code character varying(20),
    region_code character varying(20),
    founded_year smallint,
    headcount integer,
    turnover_band_mkd character varying(50),
    is_woman_owned boolean,
    is_youth_owned boolean,
    is_export_oriented boolean,
    investment_type text,
    investment_size_mkd numeric(14,2),
    cofinancing_capable_pct numeric(5,2),
    timeline_months smallint,
    project_keywords text,
    project_description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: call; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.call (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    programme_id uuid NOT NULL,
    source_feed_id uuid NOT NULL,
    reference_code text,
    title_mk text NOT NULL,
    title_sq text,
    title_en text,
    summary_mk text,
    status public.call_status DEFAULT 'draft'::public.call_status NOT NULL,
    published_at date,
    opens_at date,
    deadline_at timestamp with time zone,
    total_budget_mkd numeric(14,2),
    total_budget_eur numeric(14,2),
    grant_min_mkd numeric(14,2),
    grant_max_mkd numeric(14,2),
    cofinancing_pct numeric(5,2),
    allowed_entity_types public.entity_type[] DEFAULT '{}'::public.entity_type[] NOT NULL,
    allowed_nace_prefixes text[] DEFAULT '{}'::text[] NOT NULL,
    allowed_regions text[] DEFAULT '{}'::text[] NOT NULL,
    min_company_age_months integer,
    max_company_age_months integer,
    canonical_url text NOT NULL,
    primary_snapshot_id bigint,
    last_verified_at timestamp with time zone DEFAULT now() NOT NULL,
    extraction_confidence numeric(3,2),
    is_published boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    eligibility_gap text
);


--
-- Name: call_document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.call_document (
    id bigint NOT NULL,
    call_id uuid NOT NULL,
    snapshot_id bigint NOT NULL,
    role text NOT NULL,
    title text,
    is_primary boolean DEFAULT false NOT NULL
);


--
-- Name: call_document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.call_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: call_document_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.call_document_id_seq OWNED BY public.call_document.id;


--
-- Name: chunk; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunk (
    id bigint NOT NULL,
    snapshot_id bigint NOT NULL,
    ordinal integer NOT NULL,
    char_start integer NOT NULL,
    char_end integer NOT NULL,
    text text NOT NULL,
    embedding public.vector(1024),
    embedding_model text
);


--
-- Name: chunk_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chunk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chunk_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chunk_id_seq OWNED BY public.chunk.id;


--
-- Name: consent_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consent_record (
    id bigint NOT NULL,
    account_id uuid NOT NULL,
    purpose character varying(50) NOT NULL,
    granted boolean NOT NULL,
    policy_version character varying(50) NOT NULL,
    ip_address inet,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: consent_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.consent_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: consent_record_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.consent_record_id_seq OWNED BY public.consent_record.id;


--
-- Name: document_package; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_package (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    order_id uuid NOT NULL,
    call_id uuid NOT NULL,
    state public.review_state DEFAULT 'pending'::public.review_state NOT NULL,
    checklist jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    delivered_at timestamp with time zone
);


--
-- Name: document_template; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_template (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    programme_id uuid NOT NULL,
    slug character varying(100) NOT NULL,
    version character varying(50) NOT NULL,
    file_path text NOT NULL,
    lang public.lang DEFAULT 'mk'::public.lang NOT NULL,
    required_fields jsonb DEFAULT '[]'::jsonb NOT NULL
);


--
-- Name: eligibility_criterion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eligibility_criterion (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    call_id uuid NOT NULL,
    kind public.criterion_kind NOT NULL,
    code character varying(100),
    label_mk text NOT NULL,
    field character varying(100),
    operator character varying(20),
    value_json jsonb,
    weight numeric(4,2),
    source_quote text,
    snapshot_id bigint,
    quote_start integer,
    quote_end integer,
    source_url text,
    confidence numeric(3,2),
    extracted_at timestamp with time zone DEFAULT now() NOT NULL,
    prompt_version text,
    is_approved boolean DEFAULT false NOT NULL,
    CONSTRAINT ck_eligibility_criterion_has_citation CHECK (((NOT is_approved) OR ((snapshot_id IS NOT NULL) AND (source_quote IS NOT NULL)))),
    CONSTRAINT ck_eligibility_criterion_structured_has_predicate CHECK (((kind <> 'hard_structured'::public.criterion_kind) OR ((field IS NOT NULL) AND (operator IS NOT NULL))))
);


--
-- Name: email_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_event (
    id bigint NOT NULL,
    account_id uuid,
    kind character varying(50) NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    provider_message_id text,
    opened_at timestamp with time zone,
    bounced boolean DEFAULT false NOT NULL
);


--
-- Name: email_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.email_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: email_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.email_event_id_seq OWNED BY public.email_event.id;


--
-- Name: evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence (
    id bigint NOT NULL,
    outcome_id bigint,
    snapshot_id bigint NOT NULL,
    chunk_id bigint,
    quote text NOT NULL,
    char_start integer NOT NULL,
    char_end integer NOT NULL,
    retrieved_at timestamp with time zone DEFAULT now() NOT NULL,
    source_url text NOT NULL,
    section_ref text
);


--
-- Name: evidence_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.evidence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: evidence_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.evidence_id_seq OWNED BY public.evidence.id;


--
-- Name: generated_document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generated_document (
    id bigint NOT NULL,
    package_id uuid NOT NULL,
    template_id uuid NOT NULL,
    storage_key text NOT NULL,
    format character varying(10) NOT NULL,
    is_ai_assisted boolean DEFAULT true NOT NULL,
    human_reviewed_at timestamp with time zone,
    unfilled_fields jsonb DEFAULT '[]'::jsonb NOT NULL
);


--
-- Name: generated_document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.generated_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: generated_document_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.generated_document_id_seq OWNED BY public.generated_document.id;


--
-- Name: ingestion_run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingestion_run (
    id bigint NOT NULL,
    source_feed_id uuid NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    ok boolean,
    urls_seen integer DEFAULT 0 NOT NULL,
    urls_changed integer DEFAULT 0 NOT NULL,
    items_created integer DEFAULT 0 NOT NULL,
    items_updated integer DEFAULT 0 NOT NULL,
    queued_for_review integer DEFAULT 0 NOT NULL,
    error text
);


--
-- Name: ingestion_run_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ingestion_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ingestion_run_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ingestion_run_id_seq OWNED BY public.ingestion_run.id;


--
-- Name: invoice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoice (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    order_id uuid NOT NULL,
    kind public.invoice_kind NOT NULL,
    number character varying(50) NOT NULL,
    fiscal_year smallint NOT NULL,
    issued_at date NOT NULL,
    due_at date,
    amount_mkd numeric(12,2) NOT NULL,
    vat_mkd numeric(12,2) NOT NULL,
    total_mkd numeric(12,2) NOT NULL,
    pdf_storage_key text,
    paid_at timestamp with time zone,
    bank_reference text,
    reconciled_by uuid
);


--
-- Name: match_criterion_outcome; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_criterion_outcome (
    id bigint NOT NULL,
    match_result_id bigint NOT NULL,
    criterion_id uuid NOT NULL,
    verdict public.verdict NOT NULL,
    confidence numeric(3,2),
    decided_by character varying(10) NOT NULL,
    reason_mk text
);


--
-- Name: match_criterion_outcome_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.match_criterion_outcome_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: match_criterion_outcome_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.match_criterion_outcome_id_seq OWNED BY public.match_criterion_outcome.id;


--
-- Name: match_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_result (
    id bigint NOT NULL,
    match_run_id uuid NOT NULL,
    call_id uuid NOT NULL,
    verdict public.verdict NOT NULL,
    score numeric(6,4) NOT NULL,
    score_breakdown jsonb NOT NULL,
    rank integer NOT NULL
);


--
-- Name: match_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.match_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: match_result_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.match_result_id_seq OWNED BY public.match_result.id;


--
-- Name: match_run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    ruleset_version character varying(50) NOT NULL,
    weights_version character varying(50) NOT NULL,
    stage_reached smallint NOT NULL,
    candidates_considered integer,
    duration_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: model_call; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_call (
    id bigint NOT NULL,
    task character varying(50) NOT NULL,
    prompt_version_id character varying(100),
    model character varying(100) NOT NULL,
    cache_hit boolean DEFAULT false NOT NULL,
    input_hash character varying(64) NOT NULL,
    input_tokens integer,
    output_tokens integer,
    cost_usd numeric(10,6),
    latency_ms integer,
    ok boolean NOT NULL,
    validation_error text,
    call_id uuid,
    match_run_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: model_call_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.model_call_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: model_call_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.model_call_id_seq OWNED BY public.model_call.id;


--
-- Name: model_call_payload; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_call_payload (
    model_call_id bigint NOT NULL,
    request_json jsonb NOT NULL,
    response_json jsonb
);


--
-- Name: order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."order" (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    profile_id uuid NOT NULL,
    match_run_id uuid,
    product_id uuid NOT NULL,
    state public.order_state DEFAULT 'created'::public.order_state NOT NULL,
    amount_mkd numeric(12,2) NOT NULL,
    vat_mkd numeric(12,2) NOT NULL,
    provider character varying(30) DEFAULT 'invoice'::character varying NOT NULL,
    buyer_name text,
    buyer_address text,
    buyer_edb character varying(20),
    buyer_embs character varying(20),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    delivered_at timestamp with time zone
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sku character varying(50) NOT NULL,
    name_mk text NOT NULL,
    price_mkd numeric(12,2) NOT NULL,
    vat_rate numeric(5,2) DEFAULT 18.00 NOT NULL,
    is_recurring boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: programme; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programme (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_feed_id uuid NOT NULL,
    slug character varying(200) NOT NULL,
    name_mk text NOT NULL,
    name_sq text,
    name_en text,
    institution text NOT NULL,
    description_mk text,
    is_singleton boolean DEFAULT false NOT NULL,
    typical_cadence interval,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: prompt_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prompt_version (
    id character varying(100) NOT NULL,
    task character varying(50) NOT NULL,
    file_path text NOT NULL,
    content_sha256 character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: raw_snapshot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.raw_snapshot (
    id bigint NOT NULL,
    source_feed_id uuid NOT NULL,
    url text NOT NULL,
    content_sha256 character varying(64) NOT NULL,
    http_status integer NOT NULL,
    content_type text,
    byte_length integer,
    storage_key text NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    normalised_text text,
    normaliser_version text,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    text_source public.text_source,
    ocr_mean_confidence numeric(5,2)
);


--
-- Name: raw_snapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.raw_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: raw_snapshot_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.raw_snapshot_id_seq OWNED BY public.raw_snapshot.id;


--
-- Name: review_queue_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_queue_item (
    id bigint NOT NULL,
    kind public.review_kind NOT NULL,
    state public.review_state DEFAULT 'pending'::public.review_state NOT NULL,
    priority smallint DEFAULT 100 NOT NULL,
    call_id uuid,
    match_run_id uuid,
    order_id uuid,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    reason text NOT NULL,
    reviewer_id uuid,
    reviewer_note text,
    corrected_payload jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone
);


--
-- Name: review_queue_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.review_queue_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: review_queue_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.review_queue_item_id_seq OWNED BY public.review_queue_item.id;


--
-- Name: source_feed; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_feed (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    slug character varying(100) NOT NULL,
    name_mk text NOT NULL,
    name_en text NOT NULL,
    institution text NOT NULL,
    base_url text NOT NULL,
    access_method public.access_method NOT NULL,
    robots_checked_at timestamp with time zone,
    terms_url text,
    terms_note text,
    expected_cadence interval NOT NULL,
    staleness_sla interval NOT NULL,
    rate_limit_rps numeric(5,2) DEFAULT 0.2 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    priority smallint DEFAULT 100 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: source_health; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_health (
    source_feed_id uuid NOT NULL,
    last_attempt_at timestamp with time zone,
    last_success_at timestamp with time zone,
    last_new_item_at timestamp with time zone,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    last_error text,
    is_alerting boolean DEFAULT false NOT NULL
);


--
-- Name: subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    profile_id uuid NOT NULL,
    product_id uuid NOT NULL,
    started_on date NOT NULL,
    renews_on date NOT NULL,
    cancelled_at timestamp with time zone,
    last_alert_at timestamp with time zone
);


--
-- Name: call_document id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_document ALTER COLUMN id SET DEFAULT nextval('public.call_document_id_seq'::regclass);


--
-- Name: chunk id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk ALTER COLUMN id SET DEFAULT nextval('public.chunk_id_seq'::regclass);


--
-- Name: consent_record id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consent_record ALTER COLUMN id SET DEFAULT nextval('public.consent_record_id_seq'::regclass);


--
-- Name: email_event id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_event ALTER COLUMN id SET DEFAULT nextval('public.email_event_id_seq'::regclass);


--
-- Name: evidence id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence ALTER COLUMN id SET DEFAULT nextval('public.evidence_id_seq'::regclass);


--
-- Name: generated_document id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_document ALTER COLUMN id SET DEFAULT nextval('public.generated_document_id_seq'::regclass);


--
-- Name: ingestion_run id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingestion_run ALTER COLUMN id SET DEFAULT nextval('public.ingestion_run_id_seq'::regclass);


--
-- Name: match_criterion_outcome id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_criterion_outcome ALTER COLUMN id SET DEFAULT nextval('public.match_criterion_outcome_id_seq'::regclass);


--
-- Name: match_result id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_result ALTER COLUMN id SET DEFAULT nextval('public.match_result_id_seq'::regclass);


--
-- Name: model_call id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_call ALTER COLUMN id SET DEFAULT nextval('public.model_call_id_seq'::regclass);


--
-- Name: raw_snapshot id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_snapshot ALTER COLUMN id SET DEFAULT nextval('public.raw_snapshot_id_seq'::regclass);


--
-- Name: review_queue_item id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_queue_item ALTER COLUMN id SET DEFAULT nextval('public.review_queue_item_id_seq'::regclass);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: account pk_account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT pk_account PRIMARY KEY (id);


--
-- Name: applicant_profile pk_applicant_profile; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applicant_profile
    ADD CONSTRAINT pk_applicant_profile PRIMARY KEY (id);


--
-- Name: call pk_call; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call
    ADD CONSTRAINT pk_call PRIMARY KEY (id);


--
-- Name: call_document pk_call_document; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_document
    ADD CONSTRAINT pk_call_document PRIMARY KEY (id);


--
-- Name: chunk pk_chunk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk
    ADD CONSTRAINT pk_chunk PRIMARY KEY (id);


--
-- Name: consent_record pk_consent_record; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consent_record
    ADD CONSTRAINT pk_consent_record PRIMARY KEY (id);


--
-- Name: document_package pk_document_package; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_package
    ADD CONSTRAINT pk_document_package PRIMARY KEY (id);


--
-- Name: document_template pk_document_template; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_template
    ADD CONSTRAINT pk_document_template PRIMARY KEY (id);


--
-- Name: eligibility_criterion pk_eligibility_criterion; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_criterion
    ADD CONSTRAINT pk_eligibility_criterion PRIMARY KEY (id);


--
-- Name: email_event pk_email_event; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_event
    ADD CONSTRAINT pk_email_event PRIMARY KEY (id);


--
-- Name: evidence pk_evidence; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT pk_evidence PRIMARY KEY (id);


--
-- Name: generated_document pk_generated_document; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_document
    ADD CONSTRAINT pk_generated_document PRIMARY KEY (id);


--
-- Name: ingestion_run pk_ingestion_run; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingestion_run
    ADD CONSTRAINT pk_ingestion_run PRIMARY KEY (id);


--
-- Name: invoice pk_invoice; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT pk_invoice PRIMARY KEY (id);


--
-- Name: match_criterion_outcome pk_match_criterion_outcome; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_criterion_outcome
    ADD CONSTRAINT pk_match_criterion_outcome PRIMARY KEY (id);


--
-- Name: match_result pk_match_result; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_result
    ADD CONSTRAINT pk_match_result PRIMARY KEY (id);


--
-- Name: match_run pk_match_run; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_run
    ADD CONSTRAINT pk_match_run PRIMARY KEY (id);


--
-- Name: model_call pk_model_call; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_call
    ADD CONSTRAINT pk_model_call PRIMARY KEY (id);


--
-- Name: model_call_payload pk_model_call_payload; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_call_payload
    ADD CONSTRAINT pk_model_call_payload PRIMARY KEY (model_call_id);


--
-- Name: order pk_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT pk_order PRIMARY KEY (id);


--
-- Name: product pk_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT pk_product PRIMARY KEY (id);


--
-- Name: programme pk_programme; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programme
    ADD CONSTRAINT pk_programme PRIMARY KEY (id);


--
-- Name: prompt_version pk_prompt_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prompt_version
    ADD CONSTRAINT pk_prompt_version PRIMARY KEY (id);


--
-- Name: raw_snapshot pk_raw_snapshot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_snapshot
    ADD CONSTRAINT pk_raw_snapshot PRIMARY KEY (id);


--
-- Name: review_queue_item pk_review_queue_item; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_queue_item
    ADD CONSTRAINT pk_review_queue_item PRIMARY KEY (id);


--
-- Name: source_feed pk_source_feed; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_feed
    ADD CONSTRAINT pk_source_feed PRIMARY KEY (id);


--
-- Name: source_health pk_source_health; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_health
    ADD CONSTRAINT pk_source_health PRIMARY KEY (source_feed_id);


--
-- Name: subscription pk_subscription; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT pk_subscription PRIMARY KEY (id);


--
-- Name: account uq_account_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uq_account_email UNIQUE (email);


--
-- Name: chunk uq_chunk_snapshot_ordinal; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk
    ADD CONSTRAINT uq_chunk_snapshot_ordinal UNIQUE (snapshot_id, ordinal);


--
-- Name: document_template uq_document_template_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_template
    ADD CONSTRAINT uq_document_template_version UNIQUE (programme_id, slug, version);


--
-- Name: invoice uq_invoice_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT uq_invoice_number UNIQUE (number);


--
-- Name: match_result uq_match_result_run_call; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_result
    ADD CONSTRAINT uq_match_result_run_call UNIQUE (match_run_id, call_id);


--
-- Name: match_criterion_outcome uq_outcome_result_criterion; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_criterion_outcome
    ADD CONSTRAINT uq_outcome_result_criterion UNIQUE (match_result_id, criterion_id);


--
-- Name: product uq_product_sku; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT uq_product_sku UNIQUE (sku);


--
-- Name: programme uq_programme_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programme
    ADD CONSTRAINT uq_programme_slug UNIQUE (slug);


--
-- Name: raw_snapshot uq_raw_snapshot_url_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_snapshot
    ADD CONSTRAINT uq_raw_snapshot_url_hash UNIQUE (url, content_sha256);


--
-- Name: source_feed uq_source_feed_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_feed
    ADD CONSTRAINT uq_source_feed_slug UNIQUE (slug);


--
-- Name: ix_call_document_call; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_call_document_call ON public.call_document USING btree (call_id);


--
-- Name: ix_call_entity_types; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_call_entity_types ON public.call USING gin (allowed_entity_types);


--
-- Name: ix_call_nace; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_call_nace ON public.call USING gin (allowed_nace_prefixes);


--
-- Name: ix_call_open; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_call_open ON public.call USING btree (status, deadline_at) WHERE (is_published AND (status = 'open'::public.call_status));


--
-- Name: ix_call_programme; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_call_programme ON public.call USING btree (programme_id, published_at DESC);


--
-- Name: ix_call_regions; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_call_regions ON public.call USING gin (allowed_regions);


--
-- Name: ix_call_title_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_call_title_trgm ON public.call USING gin (title_mk public.gin_trgm_ops);


--
-- Name: ix_chunk_text_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_chunk_text_trgm ON public.chunk USING gin (text public.gin_trgm_ops);


--
-- Name: ix_consent_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_consent_account ON public.consent_record USING btree (account_id, purpose, created_at DESC);


--
-- Name: ix_criterion_call; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_criterion_call ON public.eligibility_criterion USING btree (call_id, kind);


--
-- Name: ix_email_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_email_account ON public.email_event USING btree (account_id, sent_at DESC);


--
-- Name: ix_evidence_outcome; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_evidence_outcome ON public.evidence USING btree (outcome_id);


--
-- Name: ix_ingestion_run_source_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ingestion_run_source_time ON public.ingestion_run USING btree (source_feed_id, started_at DESC);


--
-- Name: ix_invoice_unpaid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_invoice_unpaid ON public.invoice USING btree (issued_at) WHERE (paid_at IS NULL);


--
-- Name: ix_match_result_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_match_result_run ON public.match_result USING btree (match_run_id, rank);


--
-- Name: ix_match_run_profile; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_match_run_profile ON public.match_run USING btree (profile_id, created_at DESC);


--
-- Name: ix_model_call_cache; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_model_call_cache ON public.model_call USING btree (input_hash);


--
-- Name: ix_model_call_cost; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_model_call_cost ON public.model_call USING btree (created_at DESC, task);


--
-- Name: ix_order_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_order_account ON public."order" USING btree (account_id, created_at DESC);


--
-- Name: ix_order_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_order_state ON public."order" USING btree (state, created_at);


--
-- Name: ix_profile_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_profile_account ON public.applicant_profile USING btree (account_id, version DESC);


--
-- Name: ix_review_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_review_pending ON public.review_queue_item USING btree (state, priority, created_at) WHERE (state = 'pending'::public.review_state);


--
-- Name: ix_snapshot_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_snapshot_hash ON public.raw_snapshot USING btree (content_sha256);


--
-- Name: ix_snapshot_url_seen; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_snapshot_url_seen ON public.raw_snapshot USING btree (url, last_seen_at DESC);


--
-- Name: ix_snapshot_url_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_snapshot_url_time ON public.raw_snapshot USING btree (url, fetched_at DESC);


--
-- Name: ix_subscription_due; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_subscription_due ON public.subscription USING btree (renews_on) WHERE (cancelled_at IS NULL);


--
-- Name: applicant_profile fk_applicant_profile_account_id_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applicant_profile
    ADD CONSTRAINT fk_applicant_profile_account_id_account FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;


--
-- Name: call_document fk_call_document_call_id_call; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_document
    ADD CONSTRAINT fk_call_document_call_id_call FOREIGN KEY (call_id) REFERENCES public.call(id) ON DELETE CASCADE;


--
-- Name: call_document fk_call_document_snapshot_id_raw_snapshot; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_document
    ADD CONSTRAINT fk_call_document_snapshot_id_raw_snapshot FOREIGN KEY (snapshot_id) REFERENCES public.raw_snapshot(id);


--
-- Name: call fk_call_primary_snapshot_id_raw_snapshot; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call
    ADD CONSTRAINT fk_call_primary_snapshot_id_raw_snapshot FOREIGN KEY (primary_snapshot_id) REFERENCES public.raw_snapshot(id);


--
-- Name: call fk_call_programme_id_programme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call
    ADD CONSTRAINT fk_call_programme_id_programme FOREIGN KEY (programme_id) REFERENCES public.programme(id) ON DELETE RESTRICT;


--
-- Name: call fk_call_source_feed_id_source_feed; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call
    ADD CONSTRAINT fk_call_source_feed_id_source_feed FOREIGN KEY (source_feed_id) REFERENCES public.source_feed(id);


--
-- Name: chunk fk_chunk_snapshot_id_raw_snapshot; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk
    ADD CONSTRAINT fk_chunk_snapshot_id_raw_snapshot FOREIGN KEY (snapshot_id) REFERENCES public.raw_snapshot(id) ON DELETE CASCADE;


--
-- Name: consent_record fk_consent_record_account_id_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consent_record
    ADD CONSTRAINT fk_consent_record_account_id_account FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;


--
-- Name: document_package fk_document_package_call_id_call; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_package
    ADD CONSTRAINT fk_document_package_call_id_call FOREIGN KEY (call_id) REFERENCES public.call(id);


--
-- Name: document_package fk_document_package_order_id_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_package
    ADD CONSTRAINT fk_document_package_order_id_order FOREIGN KEY (order_id) REFERENCES public."order"(id) ON DELETE CASCADE;


--
-- Name: document_template fk_document_template_programme_id_programme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_template
    ADD CONSTRAINT fk_document_template_programme_id_programme FOREIGN KEY (programme_id) REFERENCES public.programme(id) ON DELETE CASCADE;


--
-- Name: eligibility_criterion fk_eligibility_criterion_call_id_call; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_criterion
    ADD CONSTRAINT fk_eligibility_criterion_call_id_call FOREIGN KEY (call_id) REFERENCES public.call(id) ON DELETE CASCADE;


--
-- Name: eligibility_criterion fk_eligibility_criterion_snapshot_id_raw_snapshot; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_criterion
    ADD CONSTRAINT fk_eligibility_criterion_snapshot_id_raw_snapshot FOREIGN KEY (snapshot_id) REFERENCES public.raw_snapshot(id);


--
-- Name: email_event fk_email_event_account_id_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_event
    ADD CONSTRAINT fk_email_event_account_id_account FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;


--
-- Name: evidence fk_evidence_chunk_id_chunk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT fk_evidence_chunk_id_chunk FOREIGN KEY (chunk_id) REFERENCES public.chunk(id);


--
-- Name: evidence fk_evidence_outcome_id_match_criterion_outcome; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT fk_evidence_outcome_id_match_criterion_outcome FOREIGN KEY (outcome_id) REFERENCES public.match_criterion_outcome(id) ON DELETE CASCADE;


--
-- Name: evidence fk_evidence_snapshot_id_raw_snapshot; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT fk_evidence_snapshot_id_raw_snapshot FOREIGN KEY (snapshot_id) REFERENCES public.raw_snapshot(id);


--
-- Name: generated_document fk_generated_document_package_id_document_package; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_document
    ADD CONSTRAINT fk_generated_document_package_id_document_package FOREIGN KEY (package_id) REFERENCES public.document_package(id) ON DELETE CASCADE;


--
-- Name: generated_document fk_generated_document_template_id_document_template; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_document
    ADD CONSTRAINT fk_generated_document_template_id_document_template FOREIGN KEY (template_id) REFERENCES public.document_template(id);


--
-- Name: ingestion_run fk_ingestion_run_source_feed_id_source_feed; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingestion_run
    ADD CONSTRAINT fk_ingestion_run_source_feed_id_source_feed FOREIGN KEY (source_feed_id) REFERENCES public.source_feed(id) ON DELETE CASCADE;


--
-- Name: invoice fk_invoice_order_id_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT fk_invoice_order_id_order FOREIGN KEY (order_id) REFERENCES public."order"(id) ON DELETE RESTRICT;


--
-- Name: invoice fk_invoice_reconciled_by_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT fk_invoice_reconciled_by_account FOREIGN KEY (reconciled_by) REFERENCES public.account(id);


--
-- Name: match_criterion_outcome fk_match_criterion_outcome_criterion_id_eligibility_criterion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_criterion_outcome
    ADD CONSTRAINT fk_match_criterion_outcome_criterion_id_eligibility_criterion FOREIGN KEY (criterion_id) REFERENCES public.eligibility_criterion(id) ON DELETE CASCADE;


--
-- Name: match_criterion_outcome fk_match_criterion_outcome_match_result_id_match_result; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_criterion_outcome
    ADD CONSTRAINT fk_match_criterion_outcome_match_result_id_match_result FOREIGN KEY (match_result_id) REFERENCES public.match_result(id) ON DELETE CASCADE;


--
-- Name: match_result fk_match_result_call_id_call; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_result
    ADD CONSTRAINT fk_match_result_call_id_call FOREIGN KEY (call_id) REFERENCES public.call(id) ON DELETE CASCADE;


--
-- Name: match_result fk_match_result_match_run_id_match_run; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_result
    ADD CONSTRAINT fk_match_result_match_run_id_match_run FOREIGN KEY (match_run_id) REFERENCES public.match_run(id) ON DELETE CASCADE;


--
-- Name: match_run fk_match_run_profile_id_applicant_profile; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_run
    ADD CONSTRAINT fk_match_run_profile_id_applicant_profile FOREIGN KEY (profile_id) REFERENCES public.applicant_profile(id) ON DELETE CASCADE;


--
-- Name: model_call fk_model_call_call_id_call; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_call
    ADD CONSTRAINT fk_model_call_call_id_call FOREIGN KEY (call_id) REFERENCES public.call(id) ON DELETE SET NULL;


--
-- Name: model_call fk_model_call_match_run_id_match_run; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_call
    ADD CONSTRAINT fk_model_call_match_run_id_match_run FOREIGN KEY (match_run_id) REFERENCES public.match_run(id) ON DELETE SET NULL;


--
-- Name: model_call_payload fk_model_call_payload_model_call_id_model_call; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_call_payload
    ADD CONSTRAINT fk_model_call_payload_model_call_id_model_call FOREIGN KEY (model_call_id) REFERENCES public.model_call(id) ON DELETE CASCADE;


--
-- Name: model_call fk_model_call_prompt_version_id_prompt_version; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_call
    ADD CONSTRAINT fk_model_call_prompt_version_id_prompt_version FOREIGN KEY (prompt_version_id) REFERENCES public.prompt_version(id);


--
-- Name: order fk_order_account_id_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_account_id_account FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE RESTRICT;


--
-- Name: order fk_order_match_run_id_match_run; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_match_run_id_match_run FOREIGN KEY (match_run_id) REFERENCES public.match_run(id);


--
-- Name: order fk_order_product_id_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_product_id_product FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: order fk_order_profile_id_applicant_profile; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_profile_id_applicant_profile FOREIGN KEY (profile_id) REFERENCES public.applicant_profile(id);


--
-- Name: programme fk_programme_source_feed_id_source_feed; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programme
    ADD CONSTRAINT fk_programme_source_feed_id_source_feed FOREIGN KEY (source_feed_id) REFERENCES public.source_feed(id);


--
-- Name: raw_snapshot fk_raw_snapshot_source_feed_id_source_feed; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_snapshot
    ADD CONSTRAINT fk_raw_snapshot_source_feed_id_source_feed FOREIGN KEY (source_feed_id) REFERENCES public.source_feed(id) ON DELETE CASCADE;


--
-- Name: review_queue_item fk_review_queue_item_call_id_call; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_queue_item
    ADD CONSTRAINT fk_review_queue_item_call_id_call FOREIGN KEY (call_id) REFERENCES public.call(id) ON DELETE CASCADE;


--
-- Name: review_queue_item fk_review_queue_item_match_run_id_match_run; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_queue_item
    ADD CONSTRAINT fk_review_queue_item_match_run_id_match_run FOREIGN KEY (match_run_id) REFERENCES public.match_run(id) ON DELETE CASCADE;


--
-- Name: review_queue_item fk_review_queue_item_order_id_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_queue_item
    ADD CONSTRAINT fk_review_queue_item_order_id_order FOREIGN KEY (order_id) REFERENCES public."order"(id) ON DELETE CASCADE;


--
-- Name: review_queue_item fk_review_queue_item_reviewer_id_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_queue_item
    ADD CONSTRAINT fk_review_queue_item_reviewer_id_account FOREIGN KEY (reviewer_id) REFERENCES public.account(id);


--
-- Name: source_health fk_source_health_source_feed_id_source_feed; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_health
    ADD CONSTRAINT fk_source_health_source_feed_id_source_feed FOREIGN KEY (source_feed_id) REFERENCES public.source_feed(id) ON DELETE CASCADE;


--
-- Name: subscription fk_subscription_account_id_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fk_subscription_account_id_account FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;


--
-- Name: subscription fk_subscription_product_id_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fk_subscription_product_id_product FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: subscription fk_subscription_profile_id_applicant_profile; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fk_subscription_profile_id_applicant_profile FOREIGN KEY (profile_id) REFERENCES public.applicant_profile(id);


--
-- PostgreSQL database dump complete
--


