#!/usr/bin/env bash
# Regenerate docs/schema.sql from the live database.
#
# The SQLAlchemy models and Alembic migrations are the source of truth; this file
# is a readable snapshot of what they produce. Run it after every migration, and
# never hand-edit the output. The reasoning behind the model lives in
# docs/data-model.md, which is written by hand.
set -euo pipefail

cd "$(dirname "$0")/.."

: "${POSTGRES_USER:=grants}"
: "${POSTGRES_DB:=grants}"

{
  echo "-- Generated by ops/dump-schema.sh from the live database. Do not edit."
  echo "-- Source of truth: app/models/ and migrations/. Rationale: docs/data-model.md."
  echo "-- Regenerate after every migration:  ./ops/dump-schema.sh"
  echo
  # pg_dump emits a random \restrict nonce on each run. Keeping it would make
  # every regeneration produce a spurious two-line diff, which is how a tracked
  # generated file stops being read. Restores use the compressed backups from
  # ops/backup.sh, not this file, so dropping that guard costs nothing here.
  docker compose exec -T postgres pg_dump \
    --schema-only --no-owner --no-privileges --no-comments \
    -U "$POSTGRES_USER" "$POSTGRES_DB" \
    | grep -vE '^\\(un)?restrict '
} > docs/schema.sql

echo "docs/schema.sql regenerated ($(wc -l < docs/schema.sql) lines)"
